# Generated by Django 5.1 on 2024-08-21 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesmedia',
            name='updated_at',
        ),
    ]
